// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_API_CarSharing.Data;

#nullable disable

namespace Web_API_CarSharing.Migrations
{
    [DbContext(typeof(CarSharingAPIDBContext))]
    [Migration("20240823214715_Seeding")]
    partial class Seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Web_API_CarSharing.Entities.Borrowing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BorrowerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Borrowings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BorrowerId = "borrower1",
                            CarId = 1,
                            EndDateTime = new DateTime(2024, 8, 23, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Great experience!",
                            StartDateTime = new DateTime(2024, 8, 23, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            BorrowerId = "borrower2",
                            CarId = 2,
                            EndDateTime = new DateTime(2024, 8, 24, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDateTime = new DateTime(2024, 8, 24, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            BorrowerId = "borrower3",
                            CarId = 3,
                            EndDateTime = new DateTime(2024, 8, 25, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Change of plans, need to cancel.",
                            StartDateTime = new DateTime(2024, 8, 25, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2
                        });
                });

            modelBuilder.Entity("Web_API_CarSharing.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Fueltype")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.Property<int>("Transmission")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Tesla",
                            Description = "A luxury electric sedan.",
                            Fueltype = 2,
                            ImageURL = "https://example.com/tesla-model-s.jpg",
                            Model = "Model S",
                            OwnerId = "owner1",
                            Seats = 5,
                            Transmission = 0,
                            Year = 2020
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Toyota",
                            Description = "A reliable compact car.",
                            Fueltype = 0,
                            ImageURL = "https://example.com/toyota-corolla.jpg",
                            Model = "Corolla",
                            OwnerId = "owner2",
                            Seats = 5,
                            Transmission = 1,
                            Year = 2019
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Ford",
                            Description = "A classic American muscle car.",
                            Fueltype = 0,
                            ImageURL = "https://example.com/ford-mustang.jpg",
                            Model = "Mustang",
                            OwnerId = "owner3",
                            Seats = 4,
                            Transmission = 0,
                            Year = 2018
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
